### ISSUE TITLE
Latest whatsapp emoji are missing in module

### ISSUE THREAD

**Issue by JerryGoyal** [Magisk-Modules-Repo/magisk-whatsapp-emojis#2]
Latest whatsapp emoji are missing for example: 
![image](https://user-images.githubusercontent.com/7106086/57153170-37abd780-6df3-11e9-8039-90d7e5bdd362.png)

**Comment by RedSc0rpi0n** [comment]
Which is missing? Your example already exists. What keyboard do you use? I use SwiftKey.

**Comment by JerryGoyal** [comment]
i use chrooma keyboard https://play.google.com/store/apps/details?id=com.gamelounge.chroomakeyboard&hl=en_US&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dchrooma+keyboard&pcampaignid=APPU_1_p3rMXJClCOOdmgfwjJngDA and i have android pie on 1+6

**Comment by RedSc0rpi0n** [comment]
I try your keyboard and think that is the problem. No pie emojis with that keyboard. Try to contact the developer or use another keyboard like gboard, swiftkey, touchpal....

**Comment by JerryGoyal** [comment]
oh i see. damn it i love that keyboard.
