### ISSUE TITLE
Module not working properly with Gboard

### ISSUE THREAD

**Issue by toot** [Magisk-Modules-Repo/magisk-whatsapp-emojis#4]
I've been absolutely happy when I discovered the update of this great module, but unfortunately it's not working properly on my device.

For a a few seconds there've been the updatet emoji, but since a few days now, the standard emojis are shown in Gboard.

Device: LG G5
Android version: 8.0.0
Gboard version: 9.0.2.290777105
Magisk version: 20.3
Magisk manager version: 7.5.1

Is there something I can do to make this module work again? Do you need any more information?

**Comment by RedSc0rpi0n** [comment]
Are the emoji displayed incorrectly only in Gboard or in general?
Try to clear the cache from Gboard and possibly uninstall and reload the module.
I personally use the SwiftKey keyboard, but I'll take a look at it with Gboard.

**Comment by RedSc0rpi0n** [comment]
Ok i think its Gboard... I've tried it myself and can see the whatsapp emojis for few seconds, now i see the google emoji (thats not my standard emojis, have a samsung device)

Same think on my HTC device, because HTC have a own emoji set like Samsung...

**Comment by toot** [comment]
I've double checked it today, with the same result.

Until a couple of weeks ago, I guess until the last emoji / Unicode update the module worked absolutely fine.

**Comment by RedSc0rpi0n** [comment]
It's not the module or any Unicode Update... I think Google forces there own emoji set on gboard

On other keyboards is all ok... SwiftKey, Touchpal and Samsung Keyboard...
